<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Administracion\Logistica.Modules.Administracion\Logistica.Modules.Administracion.csproj" />
    <ProjectReference Include="..\Modules\Envios\Logistica.Modules.Envios\Logistica.Modules.Envios.csproj" />
    <ProjectReference Include="..\Modules\Planificacion\Logistica.Modules.Planificacion\Logistica.Modules.Planificacion.csproj" />
    <ProjectReference Include="..\Modules\Ejecucion\Logistica.Modules.Ejecucion\Logistica.Modules.Ejecucion.csproj" />
    <ProjectReference Include="..\Modules\Seguimiento\Logistica.Modules.Seguimiento\Logistica.Modules.Seguimiento.csproj" />
    <ProjectReference Include="..\Modules\Deposito\Logistica.Modules.Deposito\Logistica.Modules.Deposito.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Logistica.BuildingBlocks.Infrastructure\Logistica.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
