// <auto-generated />
using System;
using Logistica.Modules.Deposito.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.Modules.Deposito.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DepositoDbContext))]
    partial class DepositoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deposito")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistica.Modules.Deposito.Domain.Recepciones.RecepcionDeposito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BultoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discrepancia")
                        .HasColumnType("text");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecibidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BultoId")
                        .IsUnique();

                    b.HasIndex("OperadorId", "EnvioId");

                    b.ToTable("Recepciones", "deposito");
                });
#pragma warning restore 612, 618
        }
    }
}
