// <auto-generated />
using System;
using System.Collections.Generic;
using Logistica.Modules.Envios.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.Modules.Envios.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnviosDbContext))]
    [Migration("20261008152416_DetalleEnvioAmpliado")]
    partial class DetalleEnvioAmpliado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("envios")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("numero_envio");

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Devoluciones.Devolucion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentoReceptor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EntregadaAlComercioEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IniciadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreReceptor")
                        .HasColumnType("text");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RecibidaEnDepositoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId")
                        .IsUnique();

                    b.ToTable("Devoluciones", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.ArchivoEvidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("OperadorId", "ComercioId", "EnvioId");

                    b.ToTable("ArchivosEvidencia", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Bulto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AltoCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AnchoCm")
                        .HasColumnType("numeric");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LargoCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoTarifa")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("OperadorId", "Codigo")
                        .IsUnique();

                    b.ToTable("Bultos", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoTarifa")
                        .HasColumnType("numeric");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VersionTarifarioId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VersionTarifarioNumero")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Destinatario", "Logistica.Modules.Envios.Domain.Envios.Envio.Destinatario#Destinatario", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Documento")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Direccion", "Logistica.Modules.Envios.Domain.Envios.Envio.Direccion#Direccion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Localidad")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Referencia")
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "CreadoEn");

                    b.HasIndex("OperadorId", "Estado");

                    b.HasIndex("OperadorId", "Numero")
                        .IsUnique();

                    b.ToTable("Envios", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.EventoEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.ToTable("EventosEnvio", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.IntentoEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotivoNoEntregaId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroIntento")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId", "NumeroIntento")
                        .IsUnique();

                    b.ToTable("IntentosEntrega", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Incidencias.Incidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolucion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResueltaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("OperadorId", "ComercioId", "EnvioId");

                    b.ToTable("Incidencias", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Devoluciones.Devolucion", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithOne()
                        .HasForeignKey("Logistica.Modules.Envios.Domain.Devoluciones.Devolucion", "EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.ArchivoEvidencia", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithMany()
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Bulto", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithMany("Bultos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.EventoEnvio", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithMany("Eventos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.IntentoEntrega", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithMany("Intentos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Logistica.Modules.Envios.Domain.Envios.PruebaEntrega", "Evidencia", b1 =>
                        {
                            b1.Property<Guid>("IntentoEntregaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CapturadaEn")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DocumentoReceptor")
                                .HasColumnType("text");

                            b1.Property<Guid?>("FirmaArchivoId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("FotoArchivoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Latitud")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Longitud")
                                .HasColumnType("numeric");

                            b1.Property<string>("NombreReceptor")
                                .HasColumnType("text");

                            b1.HasKey("IntentoEntregaId");

                            b1.ToTable("IntentosEntrega", "envios");

                            b1.WithOwner()
                                .HasForeignKey("IntentoEntregaId");
                        });

                    b.Navigation("Evidencia");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Incidencias.Incidencia", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithMany()
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Envio", b =>
                {
                    b.Navigation("Bultos");

                    b.Navigation("Eventos");

                    b.Navigation("Intentos");
                });
#pragma warning restore 612, 618
        }
    }
}
