// <auto-generated />
using System;
using System.Collections.Generic;
using Logistica.Modules.Envios.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.Modules.Envios.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnviosDbContext))]
    [Migration("20261003204352_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("envios")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("numero_envio");

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Bulto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AltoCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AnchoCm")
                        .HasColumnType("numeric");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LargoCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoTarifa")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("OperadorId", "Codigo")
                        .IsUnique();

                    b.ToTable("Bultos", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoTarifa")
                        .HasColumnType("numeric");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Destinatario", "Logistica.Modules.Envios.Domain.Envios.Envio.Destinatario#Destinatario", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Documento")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Direccion", "Logistica.Modules.Envios.Domain.Envios.Envio.Direccion#Direccion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Localidad")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Referencia")
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "Numero")
                        .IsUnique();

                    b.ToTable("Envios", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.EventoEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.ToTable("EventosEnvio", "envios");
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Bulto", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithMany("Bultos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.EventoEnvio", b =>
                {
                    b.HasOne("Logistica.Modules.Envios.Domain.Envios.Envio", null)
                        .WithMany("Eventos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Envios.Domain.Envios.Envio", b =>
                {
                    b.Navigation("Bultos");

                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
