// <auto-generated />
using System;
using Logistica.Modules.Planificacion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.Modules.Planificacion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlanificacionDbContext))]
    [Migration("20261009153012_PlanificacionCU40")]
    partial class PlanificacionCU40
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planificacion")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.BultoValidacionRuta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AltoCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AnchoCm")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BultoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LargoCm")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ValidacionRutaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VolumenM3")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "ValidacionRutaId");

                    b.HasIndex("ValidacionRutaId", "BultoId")
                        .IsUnique();

                    b.ToTable("BultosValidacionRuta", "planificacion");
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LlegadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("RutaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId")
                        .IsUnique()
                        .HasDatabaseName("UX_Paradas_EnvioActivo")
                        .HasFilter("\"Estado\" = 'Pendiente'");

                    b.HasIndex("OperadorId", "RutaId");

                    b.HasIndex("RutaId", "EnvioId")
                        .IsUnique();

                    b.ToTable("Paradas", "planificacion");
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DespachadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReservaActiva")
                        .HasColumnType("boolean");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "Fecha", "RepartidorId")
                        .IsUnique()
                        .HasDatabaseName("UX_Rutas_RepartidorReserva")
                        .HasFilter("\"ReservaActiva\" = true");

                    b.HasIndex("OperadorId", "Fecha", "VehiculoId")
                        .IsUnique()
                        .HasDatabaseName("UX_Rutas_VehiculoReserva")
                        .HasFilter("\"ReservaActiva\" = true");

                    b.ToTable("Rutas", "planificacion");
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.ValidacionRuta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AltoCargaCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AnchoCargaCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CapacidadPesoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CapacidadVolumenM3")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("FechaRuta")
                        .HasColumnType("date");

                    b.Property<decimal>("LargoCargaCm")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxParadasPorRuta")
                        .HasColumnType("integer");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid");

                    b.Property<long>("RevisionRuta")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RutaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValidadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionReglasId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "RutaId");

                    b.HasIndex("RutaId", "RevisionRuta")
                        .IsUnique();

                    b.ToTable("ValidacionesRuta", "planificacion");
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.BultoValidacionRuta", b =>
                {
                    b.HasOne("Logistica.Modules.Planificacion.Domain.Rutas.ValidacionRuta", null)
                        .WithMany("Bultos")
                        .HasForeignKey("OperadorId", "ValidacionRutaId")
                        .HasPrincipalKey("OperadorId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.Parada", b =>
                {
                    b.HasOne("Logistica.Modules.Planificacion.Domain.Rutas.Ruta", null)
                        .WithMany("Paradas")
                        .HasForeignKey("OperadorId", "RutaId")
                        .HasPrincipalKey("OperadorId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.ValidacionRuta", b =>
                {
                    b.HasOne("Logistica.Modules.Planificacion.Domain.Rutas.Ruta", null)
                        .WithMany()
                        .HasForeignKey("OperadorId", "RutaId")
                        .HasPrincipalKey("OperadorId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.Ruta", b =>
                {
                    b.Navigation("Paradas");
                });

            modelBuilder.Entity("Logistica.Modules.Planificacion.Domain.Rutas.ValidacionRuta", b =>
                {
                    b.Navigation("Bultos");
                });
#pragma warning restore 612, 618
        }
    }
}
