<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Solo para la capa Presentation (ADR-0001, addendum 2). -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Logistica.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logistica.Modules.Deposito.Contracts\Logistica.Modules.Deposito.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Logistica.SharedKernel\Logistica.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Logistica.BuildingBlocks.Infrastructure\Logistica.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

</Project>
